apiVersion: v1
kind: Service
metadata:
  name: grafana
  namespace: observability
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 3000
      nodePort: 32000   # <-- can be any free port between 30000–32767
  selector:
    app: grafana
